# Handle user input & display for feature selection demo app.
library(shiny)

shinyUI(fluidPage(
    fluidRow(
        column(12,
            h3("Are you smarter than a..."),
            h4("...machine learning feature selection algorithm?"),
            br(),
            tabsetPanel(type="tabs",
                tabPanel("Instructions",
                    br(),
                    h4("Goal:"),
                    "Let's construct a classifier to predict whether a patient will get heart disease.",
                    br(),
                    "This uses data from patients with heart disease, and controls without heart disease.",
                    br(),
                    h4("Do the feature selection:"),
                    "Help the classifier by picking out features that you think will be important.",
                    br(),
                    "Select two features, or one feature and outcome, and click ",
                    strong("[Compare features]"), " to show a plot.",
                    br(),
                    "(The first plot may take a minute or two to display.)",
                    br(),
                    "Use this to decide if two features are highly correlated, so both may not be needed.",
                    br(),
                    "You can also use what you know about the causes of heart disease to decide if a feature is important.",
                    br(),
                    h4("Train the classifier:"),
                    "When you've decided on a set of features, select just those, and then...",
                    br(),
                    "Click ", strong("[Train the classifier]"), " to train the classifier and report its accuracy.",
                    br(),
                    "(It may take a minute or two for the classifier training to complete.)",
                    br(),
                    h4("Improve:"),
                    "Try different combinations of features to get the best accuracy with fewest features.",
                    br(),
                    "Note this dataset is especially tricky for feature selection."
                ),
                tabPanel("Play!",
                    # Sidebar with checkboxes for the features.
                    column(5,
                        br(),
                        strong("Select outcome (for plotting)"),
                        checkboxInput("outcome", "Heart disease status", FALSE),
                        checkboxGroupInput("features",
                                           strong("Select features (for plotting or training)"),
                                           c("Adiposity" = "adiposity",
                                             "Age" = "age",
                                             "Alcohol use" = "alcohol",
                                             "Family history" = "famhist",
                                             "LDL cholesterol" = "ldl",
                                             "Obesity" = "obesity",
                                             "Systolic blood pressure" = "sbp",
                                             "Tobacco use" = "tobacco",
                                             "Type A behavior" = "typea")),
                        actionButton("trainButton", strong("Train the classifier")),
                        actionButton("plotButton", strong("Compare features"))
                    ),
                    # Show the resulting accuracy.
                    column(7,
                        br(),
                        strong("Classifier accuracy:"),
                        span(strong(textOutput("accuracy")), style="color:red"),
                        br(),
                        strong("Feature comparison plot:"),
                        plotOutput("featurePlot")
                    )
                ),
                tabPanel("Details",
                    br(),
                    h4("Dataset:"),
                    "The dataset used here is the South African Heart Disease Data,",
                    br(),
                    "from the ",
                    a("ElemStatLearn R package", href="http://www.inside-r.org/packages/cran/ElemStatLearn"),
                    ".",
                    br(),
                    "This is a small dataset, and few features are correlated, let alone strongly correlated.",
                    br(),
                    "It is particularly difficult for feature selection, and, in fact, for classifying.",
                    br(),
                    h4("Classifier:"),
                    "The classifier is a support vector machine with polynomial kernel,",
                    br(),
                    "from the ",
                    a("kernlab R package", href="http://www.inside-r.org/packages/cran/kernlab"),
                    ".",
                    br(),
                    "It has better accuracy on this dataset than a random forest.",
                    br(),
                    "Due to the small amount of data, the classifier is trained on the entire dataset.",
                    "So the quoted accuracy is obtained using cross-validation.",
                    br(),
                    h4("Wishlist:"),
                    "Potential improvements to this app include:",
                    br(),
                    "Implement several automated feature selection techniques,",
                    br(),
                    "and allow the user to ask which features those choose.",
                    br(),
                    "Add another dataset for which feature selection is easier.",
                    br(),
                    "Add several very different classifiers and show accuracies for all.",
                    br(),
                    "You can suggest improvements ", a("here", href="https://github.com/ptressel/feature_selection_app"), ".",
                    br(),
                    h4("To explore feature selection further:"),
                    "Excellent (if dated) ", a("review", href="http://www.jmlr.org/papers/volume3/guyon03a/guyon03a.pdf"), ".",
                    br(),
                    "Recent high-level ", a("overview", href="http://machinelearningmastery.com/an-introduction-to-feature-selection/"), ".",
                    br(),
                    "What's ", a("available in the R caret package", href="http://machinelearningmastery.com/feature-selection-with-the-caret-r-package/"), "."
                )
            )
        )
    )
))
